/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdventureEditor: typeof import('./src/components/AdventureEditor.vue')['default']
    BranchEditor: typeof import('./src/components/BranchEditor.vue')['default']
    ChoiceModal: typeof import('./src/components/ChoiceModal.vue')['default']
    ExportModal: typeof import('./src/components/ExportModal.vue')['default']
    ImportChoiceModal: typeof import('./src/components/ImportChoiceModal.vue')['default']
    StoryConverter: typeof import('./src/components/StoryConverter.vue')['default']
    StoryEditor: typeof import('./src/components/StoryEditor.vue')['default']
    StoryNameModal: typeof import('./src/components/StoryNameModal.vue')['default']
    StorySelector: typeof import('./src/components/StorySelector.vue')['default']
  }
}
